<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Assets\Art\apollo17-earth.jpg" Link="wwwroot\art\apollo17-earth.jpg" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
    <ProjectReference Include="..\CodeGlyphX\CodeGlyphX.csproj" />
  </ItemGroup>

</Project>
