coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
    patch: true

ignore:
  - "CodeGlyphX.Fuzz/**"
  - "CodeGlyphX.Benchmarks/**"
  - "CodeGlyphX.Examples/**"
