using System;

// Portions adapted from the Zint backend, Copyright (c) Robin Stuart and contributors.
// Licensed under BSD-3-Clause; see THIRD-PARTY-NOTICES.md.

namespace CodeGlyphX.HanXin;

internal static class HanXinTables {
    private static readonly ushort[] TotalValues = DecodeUInt16(
        "GQAlADIANgBFAFQAZAB1AIgAmwChALUAywDhAPkAEQErAUUBYQF9AZsBpgHFAeUBBgIoAksCbwKUAroC4QLyAhoDRANuA5oDxgPzAyIEUQRmBJcEyAT7BC8F" +
        "ZAWaBdEF6QUhBlwGlgbRBg0HSweJB8gH5QcmCGcIqgjuCDMJeQnACeAJKApxCr0KCAtUC6EL8As/DGMMtAwGDVgNrA0BDlcOrg7WDi4P");
    private static readonly ushort[] DataValues = DecodeUInt16(
        "FQAfACoALgA5AEYAVABjAHIAgwCHAJkAqwC9ANEA5QD7ABEBKQFBAVkBYgF9AZcBtAHQAe0BCwIqAkoCawJ6ApoCvgLiAgYDLANRA3gDoQOyA9sDBAQvBFsE" +
        "iAS0BOME9wQlBVgFiAW5Be0FIQZVBooGoQbYBg8HSAeAB7sH9QcwCEwIiAjFCAUJRAmECcUJCApJCmcKrArwCjYLfAvDCwsMVAx2DMAMEQAZACIAJgAxADoA" +
        "RgBRAGAAbQBxAH8AjwCdAK8AvwDRAOMA9wALAR8BKAE9AVMBagGCAZsBtQHOAegBAwIQAiwCSgJmAoYCpALDAuQCBQMUAzcDWAN9A6EDxgPsAxMEIwRLBHQE" +
        "nATFBO8EGwVHBXIFhwW0BeEFEAZABnEGoQbUBuoGHAdPB4UHuAfuByMIXAiTCKsI5AgeCVgJkgnNCQkKRgpiCqAKDQATABoAHgAlAC4ANgA/AEoAUwBXAGEA" +
        "bQB5AIcAkwChAK8AvwDNAN0A5AD1AAUBGAEqAT0BUQFmAXgBjQGYAawBxAHaAfIBCgIhAjwCVQJgAnsClAKxAs0C6gIGAyUDMQNPA3ADjgOvA88D8QMRBDQE" +
        "QwRmBIkErgTSBPcEHQVEBVYFfAWjBc0F9AUeBkcGcgadBrEG3AYIBzQHYgePB78H7gcCCDIICQAPABQAFgAbACIAKAAvADYAPQBBAEkAUQBZAGMAbQB3AIEA" +
        "jQCZAKUAqAC1AMMA0ADcAOsA+wAIARgBJwEuAT4BTgFgAXABggGVAagBuQHCAdUB6gH9ARMCKAI+AlMCXQJzAowCogK5AtEC6wIDAxwDKQNCA10DfAOSA60D" +
        "yQPmA/QDEAQtBEsEagSIBKcExgTlBPUEFAU2BVYFeAWZBb0F4AXwBRIG");
    private static readonly byte[] KValues = Convert.FromBase64String(
        "AAAADhAQERITFA4PEBARERITFBQVEBEREhITExQUFREREhITExMUFBEREhISExMTERESEhISExMTERESEhISExMRERESEhISExMRERESEhISEhER");
    private static readonly byte[] RValues = Convert.FromBase64String(
        "AAAADw8REhMUFQ8PDxERExMTExUVERASERMSFBMVFBETERMRExUTFRIUERMVEhQWERMPERMVERMVEhQPERMVEBIRExUPERMVDxESFBYPERMVFxET");
    private static readonly byte[] MValues = Convert.FromBase64String(
        "AAAAAQEBAQEBAQICAgICAgICAgICAwMDAwMDAwMDAwQEBAQEBAQEBAUFBQUFBQUFBgYGBgYGBgYGBwcHBwcHBwcICAgICAgICAgJCQkJCQkJCQoK");
    private static readonly byte[] D1Values = Convert.FromBase64String(
        "ARUEAAAAAAAAAREIAAAAAAAAAQ0MAAAAAAAAAQkQAAAAAAAAAR8GAAAAAAAAARkMAAAAAAAAARMSAAAAAAAAAQ8WAAAAAAAAASoIAAAAAAAAASIQAAAAAAAA" +
        "ARoYAAAAAAAAARQeAAAAAAAAAS4IAAAAAAAAASYQAAAAAAAAAR4YAAAAAAAAARYgAAAAAAAAATkMAAAAAAAAATEUAAAAAAAAASUgAAAAAAAAAQ4UAQ0WAAAA" +
        "AUYOAAAAAAAAAToaAAAAAAAAARgUARYSAAAAARAYARIaAAAAAVQQAAAAAAAAAUYeAAAAAAAAARoWARwYAAAAAg4UAQwUAAAAAWMSAAAAAAAAASgSASkSAAAA" +
        "AR8aASAcAAAAAhAYAQ8WAAAAAXIWAAAAAAAAAjAUAAAAAAAAAhgUARoWAAAAAhIcARIaAAAAAYMYAAAAAAAAATQWATkYAAAAAhsYAR0YAAAAAhUgARMeAAAA" +
        "AYcaAAAAAAAAATgYATkYAAAAAhwYAR8aAAAAAhYgARUgAAAAAZkcAAAAAAAAAT4aAUEcAAAAAiAcASEcAAAAAxEaARYeAAAAAVYQAVUQAAAAAUceAUgeAAAA" +
        "AiUgASMeAAAAAxQeARUgAAAAAV4SAV8SAAAAAjMWATcYAAAAAx4aAR8aAAAABBIcAREYAAAAAWgUAWkUAAAAAjkYAT0aAAAAAyEcASQeAAAABBQeARMeAAAA" +
        "AXMWAXIWAAAAAkEcAT0aAAAAAyYgASEeAAAABRMcAQ4YAAAAAX4YAX0YAAAAAkYeAUUeAAAABCEcAR0aAAAABRQeARMeAAAAAYgaAYkaAAAAAzgYATsaAAAA" +
        "BSMeAAAAAAAABhIcARUcAAAAAZQcAZUcAAAAAz0aAUAcAAAABxgUARcWAAAABhQeARUgAAAAA2sUAAAAAAAAA0EcAUgeAAAABxoWARcWAAAABxMcARQgAAAA" +
        "A3MWAAAAAAAABDgYAT8cAAAABxwYARkWAAAACBIcARUWAAAAAnQWAXoYAAAABDgYAUgeAAAABxwYASAaAAAACBIcARgeAAAAA38YAAAAAAAABTMWAT4aAAAA" +
        "Bx4aASMaAAAACBQeARUgAAAAAocaAYkaAAAABTgYATsaAAAAByEcAR4cAAAACxAYARMaAAAAA2kUAXkWAAAABT0aATkaAAAACRwYARwWAAAAChMcARIeAAAA" +
        "Ap0eAZYcAAAABUEcAT0aAAAACCEcASIeAAAAChMcAg8aAAAAA34YAXMWAAAABzMWATYWAAAACCMeASUeAAAADw8WAQoWAAAABGkUAWcUAAAABzgYAS0SAAAA" +
        "Ch8aARsaAAAAChEaAxQcARUcA4saAYkcAAAABkIcAUIeAAAACSQeASIgAAAADRMcAREgAAAABlQQAVIQAAAABkYeAUQeAAAAByMeAyEcASAcDRQeARQcAAAA" +
        "BWkUAV4SAAAABkogAUceAAAACyEcASIgAAAADRMcAxAaAAAABH8YAX4YAAAAB0IcAUIeAAAADB4YARgcARgeDxMcAREgAAAAB1QQAU4QAAAAB0YeAUIcAAAA" +
        "DCEcASAeAAAADhUgARgcAAAABXUWAXUYAAAACEIcAToaAAAACyYgASIgAAAADxQeAhEaAAAABJQcAZIcAAAACEQeAUYYAAAACiQgAyYcAAAAEBMcAxAaAAAA" +
        "BH4YAocaAAAACEYcAisaAAAADSAcAikeAAAAERMcAw8aAAAABYgaAYQYAAAABUMeBEQcAUUcDiMeASAYAAAAEhIaAxAcAQ4cA44aA40cAAAACEYeAUkgAUog" +
        "DCIeAyIaASMcEhUgARseAAAABXQWAmcUAWYUCUogAUoeAAAADiIcAiAgASAeExUgARkaAAAAB3QWAXUWAAAAC0EcAToYAAAADyYgARscAAAAFBQeARQgARUg" +
        "BogaAYIYAAAAC0IcAT4eAAAADiIcAyIgAR4eEhQeAxQcAg8aBWkUAnMWAnQWCksgAUkgAAAAECYgARscAAAAFhMcAhAeARMeBpMcAZIcAAAAC0IcAkEeAAAA" +
        "EiEcAiEeAAAAFhUgARweAAAABnQWA30YAAAAC0sgAUQeAAAADSMcBiIgAR4eFxUgARoeAAAAB2kUBF8SAAAADEMcAT8eAT4gFR8aAiEgAAAAFxUgAhgeAAAA" +
        "CnQWAAAAAAAADEogAU4eAAAAEiUgASceASkcGRUgARscAAAABX4YBHMWAXIWDEMcAkIgAUQeFSMeASceAAAAGhUgARwcAAAACX4YAXUWAAAADUsgAUQeAAAA" +
        "FCMeAyMcAAAAGxUgARweAAAACX4YAYkaAAAADUceAkQgAAAAFCUgASccASYcGBQgBRkcAAAACJMcAY0cAAAACkkgBEoeAUkeECQgBiceASUeGxUgAxQaAAAA" +
        "CYkaAYcaAAAADEYeBEsgAAAAGCMeASgcAAAAFxQgCBgeAAAADl8SAVYSAAAADUkgA00eAAAAGCMeAiMcAAAAGhUgBRUeARceCZMcAY4cAAAACkkeBkYgAUcg" +
        "GSMeAiIaAAAAHRUgBBYeAAAAC34YAYMYAAAAEEogAU8eAAAAGSYgARkeAAAAIRUgARwcAAAADmkUAWMSAAAAE0EcAUgcAAAAGCUgAigeASkeHxUgBBggAAAA" +
        "CpMcAZccAAAAD0ceA0cgAUkgGCUgAyYeASceJBMeAx0aAAAAD2kUAWMSAAAAE0YeAUAcAAAAGyYgAhkaAAAAJhQeAhIcAAAADmkUAXEWAXIWEUMeA1wgAAAA" +
        "HiMeASkeAAAAJBUgARoeARseC5IcAZIaAAAAFEYeATwaAAAAHSYgARggAAAAKBQeAhEaAAAAA4kaAYgaCn4YFkEcAUseAAAAHiUgATMeAAAAKhQeARUeAAAA" +
        "DH4YAnYWAXQWE0ogAUoeAUgcHiYgAh0eAAAAJxQgAiUaASYaDH4YA4gaAAAAFUYeAkEcAAAAIiMeASwgAAAAKhQeAhMcAhIcDH4YA3UWAXQWGT0aAj4cAAAA" +
        "IiMeASggASkgLRQeARQgARUgD2kUAnMWAnQWGUEcAUgcAAAAEiMeESUgATIgKhQeBhMcAQ8cE2kUAWUUAAAAITMWAUEWAAAAKCEcARwcAAAAMRQeARIcAAAA" +
        "EmkUAnUWAAAAGkEcAVAeAAAAIyMeAyMcASQcNBIcAiYeAAAAGlQQAAAAAAAAGkYeAAAAAAAALR8aAQkaAAAANBQeAAAAAAAAEH4YAXIWAXMWF0YeA0EcAUIc" +
        "KCMeASseAAAALhQeBxMcARAcE3QWAWkWAAAAFEYeB0IcAT8cKCMeASogASsgNhQeARMeAAAAEX4YAnMWAAAAGEYeBEogAAAAMB8aAhIaAAAANhMcBg8aAQ4a" +
        "HVQQAAAAAAAAHUYeAAAAAAAABiIeAyQeJiEcOhQeAAAAAAAAEJMcAZUcAAAAH0IcASUaAAAAMCEcARcaAAAANRQeBhMcAREcFHMWAoYYAAAAHUIcAjgaAjka" +
        "LSQeAg8cAAAAOxQeAhUgAAAAEZMcAYYaAAAAGkYeBUsgAAAALyMeATAgAAAAQBIcAiEeASMeFnMWAYUYAAAAIUEcAUocAAAAKyQeBRscAR4cORQeBRUgARgg" +
        "EogaAo4aAAAAIUIcAjEaAAAAMCMeAiYcAAAAQBQeARQgAAAAE34YAocaAYgaIEIcAjcaAjgaMSQeAhIgAAAAQRIcBRseAR0eFIkaAYIaAAAAHksgAkcgAAAA" +
        "LiMeBicgAAAAAwweRhMcAAAAFJMcAAAAAAAAI0YeAAAAAAAAMSMeBSMcAAAARhQeAAAAAAAAFYgaAZscAAAAIkYeAUAcAUEcNiMeAS0eAAAARBQeAxIcARMc" +
        "E34YBXMWAXIWIUYeA0EcAUAcNCMeAykgASggQxQeBRUgARggApYcFYgaAAAAIEYeBkEcAAAANCYgAhsgAAAASRQeAhYgAAAAFX4YBIgaAAAAHkogBkkeAAAA" +
        "NiMeBCggAAAASxQeARQcAAAAHmkUAXIWAAAAAy0WNy8UAAAAAhoaPiEcAAAATxIcBCEeAAAA");

    internal static int TotalCodewords(int version) => TotalValues[version - 1];
    internal static int DataCodewords(int version, int eccLevel) => DataValues[(eccLevel - 1) * 84 + version - 1];
    internal static int ModuleK(int version) => KValues[version - 1];
    internal static int ModuleR(int version) => RValues[version - 1];
    internal static int ModuleM(int version) => MValues[version - 1];

    internal static void GetBlockBatch(int version, int eccLevel, int batch, out int count, out int data, out int ecc) {
        var offset = (version - 1) * 36 + (eccLevel - 1) * 9 + batch * 3;
        count = D1Values[offset];
        data = D1Values[offset + 1];
        ecc = D1Values[offset + 2];
    }

    private static ushort[] DecodeUInt16(string value) {
        var bytes = Convert.FromBase64String(value);
        var result = new ushort[bytes.Length / 2];
        for (var i = 0; i < result.Length; i++) result[i] = (ushort)(bytes[i * 2] | bytes[i * 2 + 1] << 8);
        return result;
    }
}
