using System.Collections.Generic;

namespace CodeMatrix.Code39;

internal static class Code39Tables {
    public static readonly IReadOnlyDictionary<char, (int value, bool[] data)> EncodingTable = new Dictionary<char, (int, bool[])> {
        { '0', (0, new[] { true, false, true, false, false, true, true, false, true, true, false, true }) },
        { '1', (1, new[] { true, true, false, true, false, false, true, false, true, false, true, true }) },
        { '2', (2, new[] { true, false, true, true, false, false, true, false, true, false, true, true }) },
        { '3', (3, new[] { true, true, false, true, true, false, false, true, false, true, false, true }) },
        { '4', (4, new[] { true, false, true, false, false, true, true, false, true, false, true, true }) },
        { '5', (5, new[] { true, true, false, true, false, false, true, true, false, true, false, true }) },
        { '6', (6, new[] { true, false, true, true, false, false, true, true, false, true, false, true }) },
        { '7', (7, new[] { true, false, true, false, false, true, false, true, true, false, true, true }) },
        { '8', (8, new[] { true, true, false, true, false, false, true, false, true, true, false, true }) },
        { '9', (9, new[] { true, false, true, true, false, false, true, false, true, true, false, true }) },
        { 'A', (10, new[] { true, true, false, true, false, true, false, false, true, false, true, true }) },
        { 'B', (11, new[] { true, false, true, true, false, true, false, false, true, false, true, true }) },
        { 'C', (12, new[] { true, true, false, true, true, false, true, false, false, true, false, true }) },
        { 'D', (13, new[] { true, false, true, false, true, true, false, false, true, false, true, true }) },
        { 'E', (14, new[] { true, true, false, true, false, true, true, false, false, true, false, true }) },
        { 'F', (15, new[] { true, false, true, true, false, true, true, false, false, true, false, true }) },
        { 'G', (16, new[] { true, false, true, false, true, false, false, true, true, false, true, true }) },
        { 'H', (17, new[] { true, true, false, true, false, true, false, false, true, true, false, true }) },
        { 'I', (18, new[] { true, false, true, true, false, true, false, false, true, true, false, true }) },
        { 'J', (19, new[] { true, false, true, false, true, true, false, false, true, true, false, true }) },
        { 'K', (20, new[] { true, true, false, true, false, true, false, true, false, false, true, true }) },
        { 'L', (21, new[] { true, false, true, true, false, true, false, true, false, false, true, true }) },
        { 'M', (22, new[] { true, true, false, true, true, false, true, false, true, false, false, true }) },
        { 'N', (23, new[] { true, false, true, false, true, true, false, true, false, false, true, true }) },
        { 'O', (24, new[] { true, true, false, true, false, true, true, false, true, false, false, true }) },
        { 'P', (25, new[] { true, false, true, true, false, true, true, false, true, false, false, true }) },
        { 'Q', (26, new[] { true, false, true, false, true, true, false, true, true, false, false, true }) },
        { 'R', (27, new[] { true, true, false, true, false, true, false, true, true, false, false, true }) },
        { 'S', (28, new[] { true, false, true, true, false, true, false, true, true, false, false, true }) },
        { 'T', (29, new[] { true, false, true, false, true, true, false, true, true, false, false, true }) },
        { 'U', (30, new[] { true, true, false, false, true, false, true, false, true, false, true, true }) },
        { 'V', (31, new[] { true, false, true, false, true, false, true, false, true, false, true, true }) },
        { 'W', (32, new[] { true, true, false, false, true, false, true, true, false, true, false, true }) },
        { 'X', (33, new[] { true, false, true, false, true, false, true, true, false, true, false, true }) },
        { 'Y', (34, new[] { true, false, true, false, true, false, false, true, true, false, true, true }) },
        { 'Z', (35, new[] { true, true, false, false, true, false, true, false, true, true, false, true }) },
        { '-', (36, new[] { true, false, false, true, false, true, false, true, false, true, true, true }) },
        { '.', (37, new[] { true, true, false, true, false, true, false, true, false, true, false, true }) },
        { ' ', (38, new[] { true, false, false, true, false, true, false, true, true, false, true, true }) },
        { '$', (39, new[] { true, false, false, false, true, false, false, true, false, true, true, true }) },
        { '/', (40, new[] { true, false, false, false, true, false, true, false, false, true, true, true }) },
        { '+', (41, new[] { true, false, false, true, false, false, false, true, false, true, true, true }) },
        { '%', (42, new[] { true, false, true, false, false, true, false, false, true, false, false, true }) },
        { '*', (-1, new[] { true, false, false, true, false, true, true, false, true, true, false, true }) }
    };

    public static readonly IReadOnlyDictionary<char, string> ExtendedTable = new Dictionary<char, string> {
        { '\u0000', "%U" },
        { '\u0001', "$A" },
        { '\u0002', "$B" },
        { '\u0003', "$C" },
        { '\u0004', "$D" },
        { '\u0005', "$E" },
        { '\u0006', "$F" },
        { '\u0007', "$G" },
        { '\u0008', "$H" },
        { '\t', "$I" },
        { '\n', "$J" },
        { '\u000B', "$K" },
        { '\u000C', "$L" },
        { '\r', "$M" },
        { '\u000E', "$N" },
        { '\u000F', "$O" },
        { '\u0010', "$P" },
        { '\u0011', "$Q" },
        { '\u0012', "$R" },
        { '\u0013', "$S" },
        { '\u0014', "$T" },
        { '\u0015', "$U" },
        { '\u0016', "$V" },
        { '\u0017', "$W" },
        { '\u0018', "$X" },
        { '\u0019', "$Y" },
        { '\u001A', "$Z" },
        { '\u001B', "%A" },
        { '\u001C', "%B" },
        { '\u001D', "%C" },
        { '\u001E', "%D" },
        { '\u001F', "%E" },
        { '!', "/A" },
        { '\"', "/B" },
        { '#', "/C" },
        { '$', "/D" },
        { '%', "/E" },
        { '&', "/F" },
        { '\'', "/G" },
        { '(', "/H" },
        { ')', "/I" },
        { '*', "/J" },
        { '+', "/K" },
        { ',', "/L" },
        { '/', "/O" },
        { ':', "/Z" },
        { ';', "%F" },
        { '<', "%G" },
        { '=', "%H" },
        { '>', "%I" },
        { '?', "%J" },
        { '@', "%V" },
        { '[', "%K" },
        { '\\', "%L" },
        { ']', "%M" },
        { '^', "%N" },
        { '_', "%O" },
        { '`', "%W" },
        { 'a', "+A" },
        { 'b', "+B" },
        { 'c', "+C" },
        { 'd', "+D" },
        { 'e', "+E" },
        { 'f', "+F" },
        { 'g', "+G" },
        { 'h', "+H" },
        { 'i', "+I" },
        { 'j', "+J" },
        { 'k', "+K" },
        { 'l', "+L" },
        { 'm', "+M" },
        { 'n', "+N" },
        { 'o', "+O" },
        { 'p', "+P" },
        { 'q', "+Q" },
        { 'r', "+R" },
        { 's', "+S" },
        { 't', "+T" },
        { 'u', "+U" },
        { 'v', "+V" },
        { 'w', "+W" },
        { 'x', "+X" },
        { 'y', "+Y" },
        { 'z', "+Z" },
        { '{', "%P" },
        { '|', "%Q" },
        { '}', "%R" },
        { '~', "%S" },
        { '\u007F', "%T" }
    };
}
